name: Bug Report
description: Report a bug.
title: "[BUG] "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      validations:
        required: true

  - type: input
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior. (if applicable)
  - type: input
    attributes:
      label: Expected behavior
  - type: input
    attributes:
      label: Actual behavior
  - type: input
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.